config/routes.rb
RailsOnWeb::Application.routes.draw do

  resources :biz_agenters

  resources :search_items

  resources :project_items

  resources :project_cates

  resources :contacts

  resources :comments

  resources :shops

  resources :resource_items

  resources :resource_cates

  resources :product_items

  resources :product_cates

  resources :news_items

  resources :news_cates

  resources :pages

  get "home/index"
  match "about" => "pages#show", :id => 'about'
  match "sitemap" => "home#sitemap"
  match "contact" => "contacts#new"
  
  match "form" => "home#form"
  match "search" => "home#search"

  match "upload" => "resource_items#upload"
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  root :to => 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/background_job.rb
class BackgroundJob < ActiveRecord::Base

end

app/models/city.rb
class City < ActiveRecord::Base
  def test
  	'a'
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/district.rb
class District < ActiveRecord::Base
end

app/models/news_cate.rb
class NewsCate < ActiveRecord::Base
  has_many :news_items

  def self.recent(count)
    NewsCate.limit(count)
  end
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  belongs_to :news_cate

  def self.recent(count, cate = 0, image = false)
    conditions = cate > 0 ? "news_cate_id = #{cate}" : "true"
    conditions += " AND image_path IS NOT NULL" if image
    NewsItem.where(conditions).order("updated_at DESC").limit(count)
  end

  #if id = 1 return 1..9
  #if id = 5 return 1..10
  #if id = 7 return 2..12
  def self.recent_related(id)
  	low = id > 5 ? id-4 : 1
  	height = id > 10 ? id + 5 : id + (10 - id)
  	NewsItem.where("id in(#{(low..height).to_a.join(',')})").order("updated_at DESC")
  end
end

app/models/page.rb
class Page < ActiveRecord::Base

end

app/models/product_cate.rb
class ProductCate < ActiveRecord::Base
    has_many :product_items
end

app/models/product_item.rb
class ProductItem < ActiveRecord::Base
  belongs_to :product_cate

  def self.recent(count)
    ProductItem.order("updated_at DESC").limit(count)
  end

end

app/models/region.rb
class Region < ActiveRecord::Base
end

app/models/resource_cate.rb
class ResourceCate < ActiveRecord::Base
  has_many :recources_items
end

app/models/resource_item.rb
class ResourceItem < ActiveRecord::Base
  belongs_to :resource_cate
  attr_accessor :upload_file

  def self.type_hash
  	{1 => 'picture', 2 => 'file', 3 => 'video', 4 => 'audio', 5 => 'flash'}
  end

  def self.recent(count)
    ResourceItem.order("updated_at DESC").limit(count)
  end
end

app/models/search_item.rb
class SearchItem < ActiveRecord::Base
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/resource_items_controller.rb
# encoding: utf-8
require 'fileutils'
class ResourceItemsController < InheritedResources::Base
    before_filter :authenticate_admin_user!

    def create
        #upload file
        tmp = params[:resource_item][:upload_file].tempfile
        unless (file_ext = params[:resource_item][:upload_file].original_filename.split('.')).size > 1
          render :text => '错误的文件扩展名！<br/><a href="javascript: history.go(-1);">返回</a>'
          return
        end
        file_name = "#{Time.now.to_i}.#{file_ext.last.downcase}"
        file_path = File.join("public", "resource", ResourceItem.type_hash[params[:resource_item][:resource_type].to_i] || 'other', params[:resource_item][:resource_cate_id] || '0')
        unless File.exist?(file_path)
          FileUtils.mkdir_p file_path
        end
        #public/resource/picture/2/1304543534.jpg
        file = File.join(file_path, file_name)
        FileUtils.cp tmp.path, file
        #FileUtils.rm tmp.path
        
        #/resource/picture/2/1304543534.jpg
        params[:resource_item][:resource_path] = file.sub(/^public/,'')
        super
    end

    def show
        redirect_to "/admin/resource_items/#{params[:id]}"
    end
end


    # FileUtils.mkdir_p( dir, *options )
    # Options: noop verbose

    # 将生成dir目录及其所有上级目录。
    # 例如

    #   FileUtils.mkdir_p '/usr/local/lib/ruby'

    # 将生成下列所有目录(若没有的话)。
    #     * /usr
    #     * /usr/local
    #     * /usr/local/bin
    #     * /usr/local/bin/ruby

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/resource_items_helper.rb
module ResourceItemsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/admin/resource_items/_form.html.erb
<%= form_for(@resource_item, :html => {:multipart => true, :class=> 'yform'}) do |f| %>
  <% if @resource_item.errors.any? %>
  
    <div id="error_explanation">
      <h2><%= pluralize(@resource_item.errors.count, "error") %> prohibited this resource_item from being saved:</h2>

      <ul>
      <% @resource_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<fieldset>
  <legend>请选择需要上传的文件</legend>
  <%= f.file_field :upload_file %>
</fieldset>

  <div class="field">
    <%= f.label :resource_type %><br />
    <%= f.select :resource_type, [['图片', 1], ['文件', 2], ['视频', 3], ['音频', 4], ['Flash', 5]] %>
  </div>
  <div class="field">
    <%= f.label :resource_cate %><br />
    <%= f.select :resource_cate_id, ResourceCate.all.map{|cate| [cate.name, cate.id]} %>
  </div>
  <div class="field">
    <%= f.label :resource_name %><br />
    <%= f.text_field :resource_name %>
  </div>
  <div class="field">
    <%= f.label :resource_note %><br />
    <%= f.text_field :resource_note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resource_items/_form.html.erb
<%= form_for(@resource_item) do |f| %>
  <% if @resource_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource_item.errors.count, "error") %> prohibited this resource_item from being saved:</h2>

      <ul>
      <% @resource_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :resource_type %><br />
    <%= f.text_field :resource_type %>
  </div>
  <div class="field">
    <%= f.label :resource_cate %><br />
    <%= f.text_field :resource_cate %>
  </div>
  <div class="field">
    <%= f.label :resource_name %><br />
    <%= f.text_field :resource_name %>
  </div>
  <div class="field">
    <%= f.label :resource_path %><br />
    <%= f.text_field :resource_path %>
  </div>
  <div class="field">
    <%= f.label :resource_note %><br />
    <%= f.text_field :resource_note %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resource_items/edit.html.erb
<h1>Editing resource_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource_item %> |
<%= link_to 'Back', resource_items_path %>

app/views/resource_items/index.html.erb
<h1>Listing resource_items</h1>

<table>
  <tr>
    <th>Resource type</th>
    <th>Resource cate</th>
    <th>Resource name</th>
    <th>Resource path</th>
    <th>Resource note</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resource_items.each do |resource_item| %>
  <tr>
    <td><%= resource_item.resource_type %></td>
    <td><%= resource_item.resource_cate %></td>
    <td><%= resource_item.resource_name %></td>
    <td><%= resource_item.resource_path %></td>
    <td><%= resource_item.resource_note %></td>
    <td><%= link_to 'Show', resource_item %></td>
    <td><%= link_to 'Edit', edit_resource_item_path(resource_item) %></td>
    <td><%= link_to 'Destroy', resource_item, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource item', new_resource_item_path %>

app/views/resource_items/new.html.erb
<h1>New resource_item</h1>

<%= render 'form' %>

<%= link_to 'Back', resource_items_path %>

app/views/resource_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Resource type:</b>
  <%= @resource_item.resource_type %>
</p>

<p>
  <b>Resource cate:</b>
  <%= @resource_item.resource_cate %>
</p>

<p>
  <b>Resource name:</b>
  <%= @resource_item.resource_name %>
</p>

<p>
  <b>Resource path:</b>
  <%= @resource_item.resource_path %>
</p>

<p>
  <b>Resource note:</b>
  <%= @resource_item.resource_note %>
</p>


<%= link_to 'Edit', edit_resource_item_path(@resource_item) %> |
<%= link_to 'Back', resource_items_path %>

app/views/resource_items/upload.html.erb
upload