config/routes.rb
RailsOnWeb::Application.routes.draw do

  resources :biz_agenters

  resources :search_items

  resources :project_items

  resources :project_cates

  resources :contacts

  resources :comments

  resources :shops

  resources :resource_items

  resources :resource_cates

  resources :product_items

  resources :product_cates

  resources :news_items

  resources :news_cates

  resources :pages

  get "home/index"
  match "about" => "pages#show", :id => 'about'
  match "sitemap" => "home#sitemap"
  match "contact" => "contacts#new"
  
  match "form" => "home#form"
  match "search" => "home#search"

  match "upload" => "resource_items#upload"
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users

  root :to => 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/background_job.rb
class BackgroundJob < ActiveRecord::Base

end

app/models/city.rb
class City < ActiveRecord::Base
  def test
  	'a'
  end
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/district.rb
class District < ActiveRecord::Base
end

app/models/news_cate.rb
class NewsCate < ActiveRecord::Base
  has_many :news_items

  def self.recent(count)
    NewsCate.limit(count)
  end
end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
  belongs_to :news_cate

  def self.recent(count, cate = 0, image = false)
    conditions = cate > 0 ? "news_cate_id = #{cate}" : "true"
    conditions += " AND image_path IS NOT NULL" if image
    NewsItem.where(conditions).order("updated_at DESC").limit(count)
  end

  #if id = 1 return 1..9
  #if id = 5 return 1..10
  #if id = 7 return 2..12
  def self.recent_related(id)
  	low = id > 5 ? id-4 : 1
  	height = id > 10 ? id + 5 : id + (10 - id)
  	NewsItem.where("id in(#{(low..height).to_a.join(',')})").order("updated_at DESC")
  end
end

app/models/page.rb
class Page < ActiveRecord::Base

end

app/models/product_cate.rb
class ProductCate < ActiveRecord::Base
    has_many :product_items
end

app/models/product_item.rb
class ProductItem < ActiveRecord::Base
  belongs_to :product_cate

  def self.recent(count)
    ProductItem.order("updated_at DESC").limit(count)
  end

end

app/models/region.rb
class Region < ActiveRecord::Base
end

app/models/resource_cate.rb
class ResourceCate < ActiveRecord::Base
  has_many :recources_items
end

app/models/resource_item.rb
class ResourceItem < ActiveRecord::Base
  belongs_to :resource_cate
  attr_accessor :upload_file

  def self.type_hash
  	{1 => 'picture', 2 => 'file', 3 => 'video', 4 => 'audio', 5 => 'flash'}
  end

  def self.recent(count)
    ResourceItem.order("updated_at DESC").limit(count)
  end
end

app/models/search_item.rb
class SearchItem < ActiveRecord::Base
end

app/models/site.rb
class Site < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,:confirmable, :lockable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/resource_cates_controller.rb
class ResourceCatesController < InheritedResources::Base
  before_filter :authenticate_admin_user!, :except => [:index, :show]
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/helpers/resource_cates_helper.rb
module ResourceCatesHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/resource_cates/_form.html.erb
<%= form_for(@resource_cate) do |f| %>
  <% if @resource_cate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource_cate.errors.count, "error") %> prohibited this resource_cate from being saved:</h2>

      <ul>
      <% @resource_cate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resource_cates/edit.html.erb
<h1>Editing resource_cate</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource_cate %> |
<%= link_to 'Back', resource_cates_path %>

app/views/resource_cates/index.html.erb
<h1>Listing resource_cates</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @resource_cates.each do |resource_cate| %>
  <tr>
    <td><%= resource_cate.name %></td>
    <td><%= link_to 'Show', resource_cate %></td>
    <td><%= link_to 'Edit', edit_resource_cate_path(resource_cate) %></td>
    <td><%= link_to 'Destroy', resource_cate, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Resource cate', new_resource_cate_path %>

app/views/resource_cates/new.html.erb
<h1>New resource_cate</h1>

<%= render 'form' %>

<%= link_to 'Back', resource_cates_path %>

app/views/resource_cates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @resource_cate.name %>
</p>


<%= link_to 'Edit', edit_resource_cate_path(@resource_cate) %> |
<%= link_to 'Back', resource_cates_path %>